Simply and streamline rosctl.

diff --git a/root/usr/sbin/rosctl b/root/usr/sbin/rosctl
--- a/root/usr/sbin/rosctl
+++ b/root/usr/sbin/rosctl
@@ -2,6 +2,8 @@
 # Software License Agreement (BSD License)
 #
 # Copyright (c) 2013, I Heart Engineering
+# Copyright (c) 2014, Clearpath Robotics
+#
 # All rights reserved.
 #
 # Redistribution and use in source and binary forms, with or without
@@ -36,6 +38,10 @@
 DATE=`date`
 NOTIFY_USER=`ps -C gnome-session --no-headers -o user | head -1`
 USER=`id -un`
+ROS_SETUP=/etc/ros/setup.bash
+ROS_PORT=11311
+ROS_PID_FILENAME=roscore-$ROS_PORT.pid
+ROBOT_LAUNCH=/etc/ros/robot.launch
 
 # Load Environmental Varibles
 ROS_ENVVARS="/etc/ros/envvars"
@@ -43,30 +49,24 @@ if [ -f $ROS_ENVVARS ]; then
   . $ROS_ENVVARS
 fi
 
-if [ -z "$ROS_DISTRO" ]; then
-  if [ -d "/opt/ros" ]; then
-    ROS_DISTRO=$(ls /opt/ros -1 | tail -n 1)
-  fi
+# Query info about a currently-running master
+RUNNING_ROSMASTER_PID=`pgrep rosmaster | head -1`
+if ! [ -z $RUNNING_ROSMASTER_PID ]; then
+  RUNNING_ROSCORE_PID=`grep ^PPid "/proc/${RUNNING_ROSMASTER_PID}/status" | cut -f 2`
+  RUNNING_ROSCORE_USER=`ps -p $RUNNING_ROSCORE_PID --no-headers -o user`
 fi
 
-# Load Config. In order, we try:
-#  - setup file named by $ROS_SETUP environment variable.
-#  - setup file named by debconf setting (coming soon!)
-#  - /etc/ros/setup.bash
-#  - /opt/ros/$ROS_DISTRO/setup.bash
-if [ ! -z "$ROS_SETUP" ] && [ -s $ROS_SETUP ]; then
-    echo "$DATE: rosctl using setup file $ROS_SETUP"
-    source $ROS_SETUP
-elif [ -s /etc/ros/setup.bash ]; then
-    echo "$DATE: rosctl using setup file /etc/ros/setup.bash"
-    source /etc/ros/setup.bash
-elif [ ! -z "$ROS_DISTRO" ]; then
-    echo "$DATE: rosctl using setup file /opt/ros/$ROS_DISTRO/setup.bash"
-    source /opt/ros/$ROS_DISTRO/setup.bash
-else
-    echo "$DATE: rosctl can not locate setup.bash"
-    exit 1
+# Find our ROS environment setup file
+if [ ! -s "${ROS_SETUP}" ]; then
+  logger -s -p user.err "rosctl cannot find ${ROS_SETUP}, unable to launch."
+  exit 1
 fi
+
+ROS_SETUP_LINK_TARGET=$(readlink -f "${ROS_SETUP}")
+logger -s "rosctl sourcing ${ROS_SETUP} -> ${ROS_SETUP_LINK_TARGET}"
+
+source "${ROS_SETUP}"
+
 
 rosctl_usage () {
     echo "Usage: $0 start|stop|restart|status"
@@ -75,8 +75,6 @@ rosctl_usage () {
 }
 
 rosctl_notify () {
-    # 	sudo -u turtlebot -i DISPLAY=:0 /usr/bin/notify-send --urgency=normal --expire-time=1000 --icon=turtlebot --category='network.connected' '<b>ROS Launch</b>' "Starting robot on $ROS_IP"
-
     if ! [ -z $NOTIFY_USER ]; then
         if [ "$NOTIFY_USER" = "$USER" ]; then
           if [ -z $DISPLAY ]; then
@@ -89,59 +87,41 @@ rosctl_notify () {
     fi
 }
 
-rosctl_check_roscore () {
-    ROSCORE_PID=`pgrep -f "roslaunch.*core" | head -1`
-    if ! [ -z $ROSCORE_PID ]; then
-        ROSCORE_USER=`ps -p $ROSCORE_PID --no-headers -o user`
-    fi
-}
-
 rosctl_start () {
-    if ! [ -z $ROSCORE_PID ]; then
-        echo "Error: Unable to start ROS - roscore ($ROSCORE_PID) already running as $ROSCORE_USER"
+    if ! [ -z $RUNNING_ROSCORE_PID ]; then
+        logger -s -p user.err "Unable to start ROS - roscore ($RUNNING_ROSCORE_PID) already running as $RUNNING_ROSCORE_USER"
         exit 1
     fi
 
-    echo "$DATE: rosctl using ROS_HOSTNAME={$HOSTNAME}" >> $log_file
+    ROS_HOSTNAME=${HOSTNAME}
+    logger -s "Using ROS_HOSTNAME=${ROS_HOSTNAME}"
 
-    rosctl_notify "Starting robot on $ROS_IP as $USER"
-    echo "Starting robot on $ROS_IP as $USER"
+    rosctl_notify "Starting robot as $USER"
+    logger -s "Starting robot as $USER"
     if [ "$USER" = "root" ]; then
-        echo "Error: rosctl can not currently be run as root"
+        logger -s -p info.err "rosctl can not currently be run as root"
     elif [ "$USER" = "ros" ]; then
-        echo "$DATE: Starting ROS system daemon"
         export ROS_LOG_DIR=/var/log/ros
-        if [ -s ${ROS_LAUNCH:-/etc/ros/robot.launch} ]; then
-            nohup roslaunch --pid=${ROS_PID:-/var/run/ros/roscore.pid} \
-              --port=${ROS_PORT:-11311} ${ROS_LAUNCH:-/etc/ros/robot.launch} >& /tmp/ros.log &
-        else
-            nohup roslaunch --core --pid=${ROS_PID:-/var/run/ros/roscore.pid} \
-              --port=${ROS_PORT:-11311} >& /tmp/ros.log &
-        fi
+        logger -s "Starting ROS system daemon"
+        nohup roslaunch --pid=/var/run/${ROS_PID_FILENAME} \
+            --port=${ROS_PORT} ${ROBOT_LAUNCH} >& /tmp/ros.log &
     else
-        echo "$DATE: Starting ROS as user $USER"
-	if [ -z $ROSCORE_PID ]; then
-            nohup roslaunch --core \
-              --port=${ROS_PORT:-11311} >& /dev/null &
-	else
-            nohup roslaunch --core --pid=${ROS_PID} \
-              --port=${ROS_PORT:-11311} >& /dev/null &
-        fi
+        logger -s "Starting ROS as user $USER"
+        mkdir -p ${HOME}/.ros
+        nohup roslaunch  --pid=${HOME}/.ros/${ROS_PID} \
+            --port=${ROS_PORT} ${ROBOT_LAUNCH} >& /tmp/ros.log &
     fi
 }
 
 rosctl_stop () {
     rosctl_notify "Stopping robot"
-    if [ -z $ROSCORE_USER ] ; then
-        echo "Error: Unable to stop ROS - roscore is not running"
-    elif [ $ROSCORE_USER = $USER ] || [ "$USER" = "root" ] ; then
-        for i in $( rosnode list ); do
-            rosnode kill $i >& /dev/null
-        done
-        killall roslaunch >& /dev/null
-        echo "$DATE: Stopping ROS"
+    if [ -z $RUNNING_ROSCORE_PID ] ; then
+        logger -s -p user.err "Unable to stop ROS - roscore is not running"
+    elif [ $RUNNING_ROSCORE_USER = $USER ] || [ "$USER" = "root" ] ; then
+        kill $RUNNING_ROSCORE_PID
+        logger -s "Sent SIGTERM to roscore ($RUNNING_ROSCORE_PID)"
     else 
-        echo "Error: Unable to stop ROS - roscore ($ROSCORE_PID) running as $ROSCORE_USER"
+        logger -s -p user.err "Unable to stop ROS - roscore ($RUNNING_ROSCORE_PID) running as $RUNNING_ROSCORE_USER"
     fi
 }
 
@@ -156,13 +136,12 @@ rosctl_status () {
     echo "ROS Status"
     echo "----------------"
     echo "roscore"
-    ROSCORE_PID=`pgrep -f "roslaunch.*core" | head -1`
-    if [ -z $ROSCORE_PID ] ; then
-        echo "  State: Stopped"
+    if [ -z $RUNNING_ROSCORE_PID ] ; then
+        echo "  State: Not running"
     else
-        echo "  State: Started"
-        echo "  PID:   $ROSCORE_PID"
-        echo "  User:  $ROSCORE_USER"
+        echo "  State: Running"
+        echo "  PID:   $RUNNING_ROSCORE_PID"
+        echo "  User:  $RUNNING_ROSCORE_USER"
     fi
 }
 
@@ -170,7 +149,6 @@ if [ $# != 1 ] || [ -z $1 ] || [ $1 = "-h" ] || [ $1 = "--help" ] ; then
     rosctl_usage
 elif [ $1 = "start" ] || [ $1 = "stop" ] || [ $1 = "restart" ] || [ $1 = "status" ]; then
     CMD=$1
-    rosctl_check_roscore
     if [ $CMD = "start" ]; then
         rosctl_start
     elif [ $CMD = "stop" ]; then
